export const SET_LOADING_TRUE = 'SET_LOADING_TRUE'
export const SET_LOADING_FALSE = 'SET_LOADING_FALSE'
export const FETCH_USERS = 'FETCH_USERS'
export const SET_USERS = 'SET_USERS'
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const ERROR = 'ERROR'
export const DELAY = 'DELAY'
